### ISSUE TITLE
merge_noto.py

### ISSUE THREAD

**Issue by hemantagrawal25** [googlefonts/nototools#486]
Please tell me steps to merge all language files.

I have clone repo. then create individual/unhinted/ directory and copy all noto ttf files from noto-fonts report unhinted directory to individual/unhinted/  direcotry.
then I run python merge_noto.py (after copy in this directoy ) then getting following error.
Traceback (most recent call last):
  File "merge_noto.py", line 272, in <module>
    main()
  File "merge_noto.py", line 257, in main
    name = unicode(name_record.string, 'UTF-16BE')
NameError: name 'unicode' is not defined

**Comment by anthrotype** [comment]
Please retry using python 2.7. nototools does not support python 3 yet.
The `unicode` object is python2-only, it is just `str` in python 3.
