### ISSUE TITLE
merge_noto - 'NoneType' object has no attribute 'Lookup'

### ISSUE THREAD

**Issue by benbro** [googlefonts/nototools#510]
I'm getting an error when trying to use merge_noto
I've downloaded the fonts and copied to individual/unhinted
Installed with "sudo apt-get install python-nototools" ubuntu 18.04
And run the script:
```
python /usr/lib/python2.7/dist-packages/nototools/merge_noto.py
Merging Noto Sans  Regular
Table version value is a float: 1.0000; fix to use hex instead: 0x00010000
Table version value is a float: 1.0000; fix to use hex instead: 0x00010000
Table version value is a float: 1.0000; fix to use hex instead: 0x00010000
Table version value is a float: 1.0000; fix to use hex instead: 0x00010000
Table version value is a float: 1.0000; fix to use hex instead: 0x00010000
Table version value is a float: 1.0000; fix to use hex instead: 0x00010000
Table version value is a float: 1.0000; fix to use hex instead: 0x00010000
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nototools/merge_noto.py", line 268, in <module>
    main()
  File "/usr/lib/python2.7/dist-packages/nototools/merge_noto.py", line 249, in main
    font = merger.merge(regular_sources)
  File "/usr/lib/python2.7/dist-packages/fontTools/merge.py", line 912, in merge
    table = clazz(tag).merge(self, tables)
  File "/usr/lib/python2.7/dist-packages/fontTools/merge.py", line 607, in merge
    table.table.LookupList.Lookup.append(synthLookup)
AttributeError: 'NoneType' object has no attribute 'Lookup'
```

**Comment by benbro** [comment]
When installing from master I'm getting a different error:
```
python merge_noto.py
Merging Noto Sans  Regular
Table version value is a float: 1.0000; fix to use hex instead: 0x00010000
Table version value is a float: 1.0000; fix to use hex instead: 0x00010000
Table version value is a float: 1.0000; fix to use hex instead: 0x00010000
Table version value is a float: 1.0000; fix to use hex instead: 0x00010000
Table version value is a float: 1.0000; fix to use hex instead: 0x00010000
Table version value is a float: 1.0000; fix to use hex instead: 0x00010000
Table version value is a float: 1.0000; fix to use hex instead: 0x00010000
Traceback (most recent call last):
  File "merge_noto.py", line 269, in <module>
    main()
  File "merge_noto.py", line 250, in main
    font = merger.merge(regular_sources)
  File "/home/user/noto/nototools/lib/python3.6/site-packages/fontTools/merge.py", line 996, in merge
    table = clazz(tag).merge(self, tables)
  File "/home/user/noto/nototools/lib/python3.6/site-packages/fontTools/merge.py", line 159, in merge
    return m.mergeObjects(self, self.mergeMap, tables)
  File "/home/user/noto/nototools/lib/python3.6/site-packages/fontTools/merge.py", line 1044, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in tables)
  File "/home/user/noto/nototools/lib/python3.6/site-packages/fontTools/merge.py", line 48, in equal
    assert all(item == first for item in t), "Expected all items to be equal: %s" % lst
AssertionError: Expected all items to be equal: [1000, 1000, 1000, 2048, 1000, 2048, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000]
```

**Comment by ekaunt** [comment]
I was able to create a merged noto font by downloading [merge.py](https://github.com/google/fonttools/blob/master/Lib/fontTools/merge.py) and changing line [1106](https://github.com/google/fonttools/blob/2b7656550d03b486c08a54d05d08a0b3b5c025bb/Lib/fontTools/merge.py#L1106) to `args = sys.argv[2:]` and line [1123](https://github.com/google/fonttools/blob/2b7656550d03b486c08a54d05d08a0b3b5c025bb/Lib/fontTools/merge.py#L1123) to `outfile = sys.argv[1]`.

Then clone [noto-fonts](https://github.com/googlefonts/noto-fonts) into the same dir, and run

```bash
# change the Sans to Serif in the next 2 lines to generate the Noto Serif 
cp noto-fonts/hinted/NotoSans/NotoSans-Regular.ttf merged.ttf
i=1;b=0;f=();for font in noto-fonts/hinted/*Sans*/*-Regular.*; do
        echo "$((i++)) $font";
        function fail() {
                f+=($font);echo "$i - $font failed. $((++b)) total failed fonts";continue;
        }
        python merge.py merged-temp.ttf merged.ttf "$font" || fail
        # if we were successful in merging the font, then set the merged font. else forget about the failed temp file
        last="$font"
        cp merged-temp.ttf merged.ttf
        echo "Successful! $i $font";
done
echo "$b fonts failed: ${f[*]}"
```

It's not perfect, and not all fonts merge, but at least most of them do. 

Here are the sans & serif font files I was able to generate, because the internet seems to be completely void of merged Noto fonts…

[noto-merged.zip](https://github.com/googlefonts/nototools/files/5156874/noto-merged.zip)
